<?php 
$this->headTitle()->setAutoEscape(false);
echo $this->partial('manual/toc', array('form' => $this->form, 'locales' => $this->locales, 'code' => $this->code, 'version' => $this->version));
echo $this->partial('manual/header', array('active' => 'manual')) ?>

<?php echo $this->dynamicHeader('subPageMainHeader', "Programmer's Reference Guide") ?>

<div class="dotted-line"></div>

<div id="manual-container" class="tundra<?php echo (in_array($this->code, array('ar'))) ? ' rtl-language' : '' ?>">
    <?php echo $this->render($this->page); ?>
    <?php 
        echo $this->render('manual/_comments.phtml');
        echo $this->render('manual/_comment-form.phtml');
    ?>
</div>

<?php
$this->dojo()->addOnLoad('function(){
    dojo.query("div.comment-form form").style({display: "none"});
    dojo.query("div.comment-form h4").onclick(function(n){
        dojo.query("div.comment-form form").wipeIn({
            duration: 500
        }).play();
        dojo.query(".comment-form h4 span.expand").toggleClass("hidden");
    });
    zf.ManualNavigation.generate();
}');

$version = $this->mVersion . '.0';
if (version_compare($version, '1.9.0', '<')):
    $this->dojo()->requireModule('dojox.highlight.languages.pygments._www')
                 ->addStylesheet('/js/dojox/highlight/resources/pygments/borland.css');
    $this->dojo()->onLoadCaptureStart(); ?>
function(){
    dojo.query(".programlisting .cdata").forEach(function(n){
        var c = dojo.create("code");
        dojo.query("pre", n).forEach(function(p){
            c.innerHTML = p.innerHTML;
            dojo.empty(p);
            dojo.place(c, p, "first");
        });
        dojox.highlight.init(c);
    });
}
<?php 
    $this->dojo()->onLoadCaptureEnd();
endif;

